# constants will be declared here

WIDTH = 700
HEIGHT = 600

BG_COLOR = "Grey"
TITLE = "Shooting Game App 1.0"

BULLET_SPEED = 10
TARGET_SPEED = 1.5

FPS = 30
FRAME_TIME = int(1000 / FPS)
STARTING_LIVES = 5
LEVEL_SCORE = 5
MAX_TARGETS = 5
START_LEVEL = 1